remove core_lib, functions back to bar

diff --git a/bar b/bar
--- a/bar
+++ b/bar
@@ -24,10 +24,11 @@ function bar_main ## [Rulefile] [Rule [Arguments]] - loads a Barf file and execu
     declare -gx  BARF_FILE                 ## the Barf file used
     declare -gxr BAR_PWD="$PWD"            ## initial working directory
     declare -gxi BAR_VERBOSITY_LEVEL="${BAR_VERBOSITY_LEVEL:-2}"
+    declare -gA  BAR_REQUIRE_LOADED
 
     # bootstrap/load std_lib (which defines 'require')
     # shellcheck disable=SC1091
-    find_toplevel && source "$BARF_DIR/core_lib"
+    find_toplevel
     debug "using Barf directory: $BARF_DIR"
     # the std_lib and rule_lib are omnipresent other modules don't need to require it
     require std_lib rule_lib
@@ -66,17 +67,20 @@ function bar_main ## [Rulefile] [Rule [Arguments]] - loads a Barf file and execu
     }
 
     if rule_exists "$initial_rule"; then
+        rule_exists SETUP && { rule_eval SETUP || die "SETUP failed" ; }
+        rule_exists PREPROCESS && { rule_eval PREPROCESS || die "PREPROCESS failed" ; }
+
         rule_eval "$initial_rule" "$@" || rc=$?
         if (( "$rc" == 0 )); then
             success "$initial_rule" "$@"
+            unset "BAR_RULES_UNSEALED[POSTPROCESS]"
+            rule_exists POSTPROCESS && { rule_eval POSTPROCESS || error "POSTPROCCESS failed" ; }
         else
             failure "$initial_rule" "$@"
         fi
 
-        unset "BAR_RULES_UNSEALED[POSTPROCESS]"
-        rule_exists POSTPROCESS && rule_eval POSTPROCESS
         unset "BAR_RULES_UNSEALED[CLEANUP]"
-        rule_exists CLEANUP && rule_eval CLEANUP
+        rule_exists CLEANUP && { rule_eval CLEANUP || error "CLEANUP failed" ; }
         return $rc
     else
         die "No Barf file found in current directory and no rule defined.
@@ -112,6 +116,7 @@ function find_toplevel
             break
         fi
     done
+
     warn "No Barf.d directory found, trying original/installed"
 
     if [[ ! -d "$BARF_DIR" ]]; then
@@ -120,4 +125,92 @@ function find_toplevel
     fi
 }
 
+function source_info # [N] - returns file:line N (or 0) up the bash call stack
+{
+    echo "${BASH_SOURCE[$((${1:-0}+1))]}:${BASH_LINENO[$((${1:-0}))]}:${FUNCNAME[$((${1:-0}+1))]:+${FUNCNAME[$((${1:-0}+1))]}:}"
+}
+
+function require
+{
+    trace "$*"
+    declare -i rc=0
+    local mod
+    #shellcheck disable=2167,2165
+    for mod in "$@"; do
+        for mod in "$BARF_DIR/"$mod; do
+            local modname="${mod##*/}"
+            if [[ ! -v BAR_REQUIRE_LOADED["$modname"] ]]; then
+                if [[ -f "$mod" ]]; then
+                    trace "loading: $mod"
+                    BAR_REQUIRE_LOADED["$modname"]=pending
+                    # shellcheck disable=SC1090 # dynamic source
+                    source "$mod" && BAR_REQUIRE_LOADED["$modname"]=true
+                else
+                    BAR_REQUIRE_LOADED["$modname"]=false
+                    rc=1
+                fi
+            fi
+        done
+    done
+    return $rc
+}
+
+function DBG ## [message..] - for print-style debugging, should not be present in production code
+{
+    echo -e "\033[1;37;41m  DBG:\033[0m $(source_info 1) $*" >&2
+}
+
+function die ## [message..] - prints 'message' to stderr and exits with failure
+{
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 0 ]]; then
+        echo -e "\033[1;91mPANIC:\033[0m $(source_info 1) $*" >&2
+    fi
+    exit 1
+}
+
+function error ## [message..] - may print a error message to stderr and return failure
+{
+    # TODO: (( ))
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 0 ]]; then
+        echo -e "\033[1;31mERROR:\033[0m $(source_info 1) $*" >&2
+    fi
+}
+
+function warn ## [message..] - may print an warning to stderr
+{
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 1 ]]; then
+        echo -e "\033[1;35m WARN:\033[0m $*" >&2
+    fi
+}
+
+function trace ## [message] - may prints a trace message to stderr
+{
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 5 ]]; then
+        echo -e "\033[1;96mTRACE:\033[0m $(source_info 1) $*" >&2
+    fi
+}
+
+function note ## [message..] - may print an important notice to stderr
+{
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 1 ]]; then
+        echo -e "\033[1;35m NOTE:\033[0m $*" >&2
+    fi
+}
+
+function info ## [message..] - may print an informal message to stderr
+{
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 3 ]]; then
+        echo -e "\033[1;34m INFO:\033[0m $*" >&2
+    fi
+}
+
+function debug ## [message..] - may print a debug message to stderr
+{
+    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 4 ]]; then
+        echo -e "\033[1;36mDEBUG:\033[0m $(source_info 1) $*" >&2
+    fi
+}
+
 bar_main "$@"
+
+
