mixed style and formatting fixes

diff --git a/bar b/bar
--- a/bar
+++ b/bar
@@ -184,13 +184,13 @@ function require
 }
 
 # placeholder, overwritten by tty_lib when present
-tty_newline() { :; }
+function tty_newline { :; }
 
 function DBG ## [message..] - for print-style debugging, should not be present in production code
 {
     {
         tty_newline
-        echo "${TTYERR[r_R]:-}${TTYERR[__B]:-}  DBG:${TTYERR[n]:-} $(source_info 1) $*"
+        echo "${TTYERR[ce]:-}${TTYERR[r_R]:-}${TTYERR[__B]:-}  DBG:${TTYERR[n]:-} $(source_info 1) $*"
     } >&2
 }
 
@@ -198,7 +198,7 @@ function die ## [message..] - prints 'message' to stderr and exits with failure
 {
     if (( BAR_VERBOSITY_LEVEL > 0 )); then
         tty_newline
-        echo "${TTYERR[R_B]:-}PANIC:${TTYERR[n]:-} $(source_info 1) $*"
+        echo "${TTYERR[ce]:-}${TTYERR[R_B]:-}PANIC:${TTYERR[n]:-} $(source_info 1) $*"
     fi >&2
     exit 1
 }
@@ -207,7 +207,7 @@ function error ## [message..] - may print a error message to stderr and return f
 {
     if (( BAR_VERBOSITY_LEVEL > 0 )); then
         tty_newline
-        echo "${TTYERR[r_B]:-}ERROR:${TTYERR[n]:-} $(source_info 1) $*"
+        echo "${TTYERR[ce]:-}${TTYERR[r_B]:-}ERROR:${TTYERR[n]:-} $(source_info 1) $*"
     fi >&2
 }
 
@@ -215,7 +215,7 @@ function warn ## [message..] - may print an warning to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 1 )); then
         tty_newline
-        echo "${TTYERR[m_B]:-} WARN:${TTYERR[n]:-} $*" >&2
+        echo "${TTYERR[ce]:-}${TTYERR[m_B]:-} WARN:${TTYERR[n]:-} $*" >&2
     fi >&2
 }
 
@@ -223,7 +223,7 @@ function note ## [message..] - may print an important notice to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 2 )); then
         tty_newline
-        echo "${TTYERR[m_B]:-} NOTE:${TTYERR[n]:-} $*"
+        echo "${TTYERR[ce]:-}${TTYERR[m_B]:-} NOTE:${TTYERR[n]:-} $*"
     fi >&2
 }
 
@@ -231,7 +231,7 @@ function info ## [message..] - may print an informal message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 3 )); then
         tty_newline
-        echo "${TTYERR[b_B]:-} INFO:${TTYERR[n]:-} $*"
+        echo "${TTYERR[ce]:-}${TTYERR[b_B]:-} INFO:${TTYERR[n]:-} $*"
     fi >&2
 }
 
@@ -239,7 +239,7 @@ function debug ## [message..] - may print a debug message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 4 )); then
         tty_newline
-        echo "${TTYERR[c_B]:-}DEBUG:${TTYERR[n]:-} $(source_info 1) $*"
+        echo "${TTYERR[ce]:-}${TTYERR[c_B]:-}DEBUG:${TTYERR[n]:-} $(source_info 1) $*"
     fi >&2
 }
 
@@ -247,7 +247,7 @@ function trace ## [message] - may prints a trace message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 5 )); then
         tty_newline
-        echo "${TTYERR[C_B]:-}TRACE:${TTYERR[n]:-} $(source_info 1) $*"
+        echo "${TTYERR[ce]:-}${TTYERR[C_B]:-}TRACE:${TTYERR[n]:-} $(source_info 1) $*"
     fi >&2
 }
 
