Add the remaining docs, oncluding minor fixes on the go

diff --git a/Bar.d/lock b/Bar.d/lock
--- a/Bar.d/lock
+++ b/Bar.d/lock
@@ -1,20 +1,15 @@
 #!/bash
-## managing lockfiles
-##
 
-# Lockfiles: Manage ownership of resources.  We can create or wait on a lockfile with
-# lock_wait and remove it with lock_remove.  These locks are recursive the same process can
-# lock_wait on the same lockfile multiple times which must be paired with the same numbers of
-# lock_remove to unlock it.  lock_next does hand over hand locking locking a new lockfile and
-# then releases the original one.  lock_remove takes a name as parameter and removes the
-# lockfile if it is owned by the current process.  Locks can be send atomically to another
-# process. lock_receive blocks until the the process gets the lock, lock_send registers the
-# lock to be send to a process. It will be send at the final lock_remove in the sending
-# process.
+### Library for managing lockfiles
+
 declare -gA LOCK_REC=()
 
-function lock_wait #api <lockname> - lock a lockfile, waits until we have the lock
+function lock_wait ## <lockname> - Waits until we have the lock on a lockfile.
 {
+    ## '.lock' is automatically appended to the 'lockname'.
+    ## These locks are recursive the same process can lock_wait on the same lockfile multiple
+    ## times which must be paired with the same numbers of 'lock_remove' to unlock it.
+
     # shellcheck disable=SC2155
     local lockfile="$(realpath -s "$1.lock")"
     if (( LOCK_REC["$lockfile"] > 0 )); then
@@ -68,8 +63,9 @@ function lock_wait #api <lockname> - lock a lockfile, waits until we have the lo
     trace "locked: $1 as $BASHPID"
 }
 
-function lock_try_norec #api <lockname> - try to lock a lockfile non recursively, will not wait, fails when we already have the lock
+function lock_try_norec ## <lockname> - try to lock a lockfile non recursively.
 {
+    ## Will not wait, fails when we already have the lock
     # shellcheck disable=SC2155
     local lockfile="$(realpath -s "$1.lock")"
     if (( LOCK_REC["$lockfile"] > 0 )); then
@@ -105,14 +101,36 @@ function lock_try_norec #api <lockname> - try to lock a lockfile non recursively
     trace "locked: $1 as $BASHPID"
 }
 
-function lock_next # old new - hand over hand locking
+function lock_next # <old> <new> - hand over hand locking
 {
+    ## Locks 'new' and then removes the 'old' locck.
     lock_wait "$2"
     lock_remove "$1"
 }
 
-function lock_receive #api <lock> - to be called in a subprocess before sending the lock
+function lock_send ## <lock> <who> - Sends a 'lock' to another process with pid 'who'.
 {
+    ## Locks can be send atomically to another process. 'lock_send' registers the lock to be
+    ## send to a process, the lock will be send at the final lock_remove in the sending
+    ## process when all recursive locks are freed. Note that to obtain the 'who' pid the
+    ## receiver has to be started first.
+    # shellcheck disable=SC2155
+    local lockfile="$(realpath -s "$1.lock")"
+    (( LOCK_REC["$lockfile"] > 0 )) || die "lock $1 is not locked by $BASHPID"
+
+    # shellcheck disable=SC2155
+    local send_to=$(<"$lockfile")
+    [[ "$send_to" != "$BASHPID" ]] && {
+        error "lock $1 is already send to $send_to"
+        return 1
+    }
+
+    echo -n "$2" > "$lockfile"
+}
+
+function lock_receive ## <lock> - Wait for lock send by another process.
+{
+    ## Blocks until the the sender removed all uses of 'lock',
     # shellcheck disable=SC2155
     local lockfile="$(realpath -s "$1.lock")"
 
@@ -136,24 +154,10 @@ function lock_receive #api <lock> - to be called in a subprocess before sending 
     done
 }
 
-function lock_send #api <lock> <who> - to be called from parent after child forked
+function lock_remove ## <lock> - Unlocks 'lock'.
 {
-    # shellcheck disable=SC2155
-    local lockfile="$(realpath -s "$1.lock")"
-    (( LOCK_REC["$lockfile"] > 0 )) || die "lock $1 is not locked by $BASHPID"
-
-    # shellcheck disable=SC2155
-    local send_to=$(<"$lockfile")
-    [[ "$send_to" != "$BASHPID" ]] && {
-        error "lock $1 is already send to $send_to"
-        return 1
-    }
-
-    echo -n "$2" > "$lockfile"
-}
-
-function lock_remove #api {name} - remove a lockfile, unlock
-{
+    ## 'lock_remove' must be paired with the same numbers of earlier 'lock_wait'. Only the
+    ## last 'lock_remove' will release the lockfile.
     # shellcheck disable=SC2155
     local lockfile="$(realpath -s "$1.lock")"
 
diff --git a/Bar.d/testdir b/Bar.d/testdir
--- a/Bar.d/testdir
+++ b/Bar.d/testdir
@@ -1,19 +1,35 @@
 #!/bash
 
+### Creating an isolated directory for testing.
+###
+### Unlike other frameworks which do 'pre-commit' processing bar will not modify, block or
+### stash the users workdir. Instead it creates and manages directories which become populated
+### with the projects files. These testdirs also act as caches for build artifacts an can be
+### seeded from previous runs to increase build/test speed. Testdirs are automatically garbage
+### collected, only a few most recent used ones are kept for inspection and seeding new build.
+###
+### Testdirs are created from git 'treeish' objects. Thus git is mandatory.
+### Testdirs are created in the git toplevel and have the name constructed from
+### '$TESTDIR_PREFIX-<timestamp>-<treehash>/'
+
 require lock
 require git_lib
 
-declare -gx TESTDIR_PREFIX="${TESTDIR_PREFIX:-.test}"
-declare -gx TESTDIR_KEEP="${TESTDIR_KEEP:-5}"
-declare -gx TESTDIR
-declare -gx TESTDIR_PREV
+declare -gx TESTDIR_PREFIX="${TESTDIR_PREFIX:-.test}" ## Prefix used for testdirs.
+declare -gx TESTDIR_KEEP="${TESTDIR_KEEP:-5}"         ## How many old testdirs.
+declare -gx TESTDIR                                   ## Path to the current testdir.
+declare -gx TESTDIR_PREV                              ## Path to the previous testdir if exits.
 
-# create and change into testdir
+## [treeish] - Sets up a test directory change dir into it.
+## Must be called from the git toplevel. Takes an optional treeish to construct the testdir
+## from. When no treeish is given then current index is used.  After creation the
+## 'testdir_enter_hook' rule is evaluated. This rule is used to prep/populate/seed the
+## testdir. When a previous testdir exists then 'TESTDIR_PREV' point to it, the hook can use
+## that as source for populating already build artifacts.
 rule testdir_enter: is_git_toplevel -
-# other modules can hook into here
 rule testdir_enter: testdir_enter_hook??
 
-function testdir_enter # treeish - Sets up a test directory change dir into it.
+function testdir_enter
 {
     trace "$*"
     lock_wait "$BAR_TOPLEVEL/.bar"
@@ -37,19 +53,25 @@ function testdir_enter # treeish - Sets up a test directory change dir into it.
     fi
     lock_next "$BAR_TOPLEVEL/.bar" "$TESTDIR/.bar"
     rule CLEANUP: -- "cd '$(git_toplevel)'; lock_remove '$TESTDIR/.bar'; testdir_gc"
-    cd "$TESTDIR" || { error "cant change into $TESTDIR"; return 1; }
+    cd "$TESTDIR" || { error "can't change into $TESTDIR"; return 1; }
 }
 
+## Succeeds when a testdir is in use and current working directory is inside it.
 function is_testdir_used
 {
-    [[ -v TESTDIR && "$PWD" = "$TESTDIR"* ]]
+    [[ -v TESTDIR && "$PWD/" = "$TESTDIR/"* ]]
 }
 
-function testdir_gc # - cleanup old testdirs
+function testdir_gc ## Cleanup old testdirs.
 {
+    ## Removed old unused testdirs. This is called automatically. It is only necessary to
+    ## manually call this when testdirs piled up because they where in use or when
+    ## 'TESTDIR_KEEP' was decremented.
     local testdir
     lock_wait "$BAR_TOPLEVEL/.bar"
-    find "$(git_toplevel)" -name "${TESTDIR_PREFIX}*" -type d -print0 | sort -z -n | head -z -n -$((TESTDIR_KEEP)) |
+    find "$(git_toplevel)" -maxdepth 1 -name "${TESTDIR_PREFIX}*" -type d -print0 |
+        sort -z -n |
+        head -z -n -$((TESTDIR_KEEP)) |
         while IFS= read -r -d '' testdir; do
             if lock_try_norec "$testdir/.bar"; then
                 info "deleting: $testdir"
@@ -61,11 +83,12 @@ function testdir_gc # - cleanup old testdirs
     lock_remove "$BAR_TOPLEVEL/.bar"
 }
 
-function testdir_clean # - cleanup all testdirs
+function testdir_clean ## Cleanup all testdirs.
 {
+    ## Removes all unused testdirs.
     local testdir
     lock_wait "$BAR_TOPLEVEL/.bar"
-    find "$(git_toplevel)" -name "${TESTDIR_PREFIX}*" -type d -print0 |
+    find "$(git_toplevel)" -maxdepth 1 -name "${TESTDIR_PREFIX}*" -type d -print0 |
         while IFS= read -r -d '' testdir; do
             if lock_try_norec "$testdir/.bar"; then
                 info "deleting: $testdir"
@@ -77,7 +100,7 @@ function testdir_clean # - cleanup all testdirs
     lock_remove "$BAR_TOPLEVEL/.bar"
 }
 
-function testdir_list # - list all testdirs
+function testdir_list ## Lists all testdirs.
 {
-    find "$(git_toplevel)" -name "${TESTDIR_PREFIX}*" -type d
+    find "$(git_toplevel)" -maxdepth 1 -name "${TESTDIR_PREFIX}*" -type d
 }
