WIP: tty_lib for terminal control codes/tty handling

diff --git a/Bar.d/std_lib b/Bar.d/std_lib
--- a/Bar.d/std_lib
+++ b/Bar.d/std_lib
@@ -66,30 +66,31 @@ function called_as
     return 1
 }
 
+# elusive progress notice
 function progress ## [message..] -
 {
     if (( BAR_CHECK_LEVEL > 0 )); then
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -en "\033[1;90m  RUN: $*\033[0m\r" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && tty_echo -n "${TTYERR[K_B]:-}  RUN: $*${TTYERR[cr]:-}" >&2
     else
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -en "\033[1;90m  RUN: $*\033[0m\r" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && tty_echo -n "${TTYERR[K_B]:-}  RUN: $*${TTYERR[cr]:-}" >&2
     fi
 }
 
 function success ## [message..] -
 {
     if (( BAR_CHECK_LEVEL > 0 )); then
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -e "\033[2K\033[1;32mCHECK:\033[0m $*" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-}CHECK:${TTYERR[n]:-} $*" >&2
     else
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -e "\033[2K\033[1;32m   OK:\033[0m $*" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-}   OK:${TTYERR[n]:-} $*" >&2
     fi
 }
 
 function failure ## [message..] -
 {
     if (( BAR_CHECK_LEVEL > 0 )); then
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -e "\033[2K\033[1;90mCHECK: \033[9m$*\033[0m" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -e "${TTYERR[ce]:-}${TTYERR[K_B]:-}CHECK: ${TTYERR[__S]:-}$*${TTYERR[n]:-}" >&2
     else
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -e "\033[2K\033[1;31m FAIL:\033[0m $*" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -e "${TTYERR[ce]:-}${TTYERR[r_B]:-} FAIL:${TTYERR[n]:-} $*" >&2
     fi
 }
 
@@ -99,13 +100,12 @@ function uncond_call ## <rc> [message..] -
     shift
     if (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )); then
         if (( rc == 0 )); then
-            echo -e "\033[1;32m EVAL:\033[0m $*" >&2
+            echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-} EVAL:${TTYERR[n]:-} $*" >&2
         else
-            echo -e "\033[1;90m EVAL:\033[0m $*" >&2
+            echo -e "${TTYERR[ce]:-}${TTYERR[K_B]:-} EVAL:${TTYERR[n]:-} $*" >&2
         fi
     fi
 }
-
 
 function rule_autoload ## <name>
 {
@@ -115,7 +115,7 @@ function rule_autoload ## <name>
     modname="${modname#has_}"
     modname="${modname#try_}"
     modname="${modname%%_*}"
-    require --try "$modname"
+    require --opt "$modname"
 
     # when $name exists as command or function then create a rule for that
     if ! rule_exists "$1" && command -v "$1" >/dev/null ; then
@@ -123,11 +123,6 @@ function rule_autoload ## <name>
     fi
     rule_exists "$1" || die "no rule, command or function '$1' defined"
 }
-
-
-
-
-
 
 # checks whenever a shell command is in PATH
 function is_command_installed
diff --git a/bar b/bar
--- a/bar
+++ b/bar
@@ -26,6 +26,10 @@ function bar_main ## [Rulefile] [Rule [Arguments]] - loads a Barf file and execu
     declare -gxr BAR_PWD="$PWD"            ## initial working directory
     declare -gxi BAR_VERBOSITY_LEVEL="${BAR_VERBOSITY_LEVEL:-2}"
     declare -gA  BAR_REQUIRE_LOADED
+    # shellcheck disable=2034
+    declare -gA TTYCTL TTYNIL
+    # shellcheck disable=2034
+    declare -g TTYOUT TTYERR
 
     # bootstrap/load std_lib (which defines 'require')
     # shellcheck disable=SC1091
@@ -179,13 +183,13 @@ function require
 
 function DBG ## [message..] - for print-style debugging, should not be present in production code
 {
-    echo -e "\033[1;37;41m  DBG:\033[0m $(source_info 1) $*" >&2
+    echo "${TTYERR[r_R]:-}${TTYERR[__B]:-}  DBG:${TTYERR[n]:-} $(source_info 1) $*" >&2
 }
 
 function die ## [message..] - prints 'message' to stderr and exits with failure
 {
     if (( BAR_VERBOSITY_LEVEL > 0 )); then
-        echo -e "\033[1;91mPANIC:\033[0m $(source_info 1) $*" >&2
+        echo "${TTYERR[R_B]:-}PANIC:${TTYERR[n]:-} $(source_info 1) $*" >&2
     fi
     exit 1
 }
@@ -193,42 +197,42 @@ function die ## [message..] - prints 'message' to stderr and exits with failure
 function error ## [message..] - may print a error message to stderr and return failure
 {
     if (( BAR_VERBOSITY_LEVEL > 0 )); then
-        echo -e "\033[1;31mERROR:\033[0m $(source_info 1) $*" >&2
+        echo "${TTYERR[r_B]:-}ERROR:${TTYERR[n]:-} $(source_info 1) $*" >&2
     fi
 }
 
 function warn ## [message..] - may print an warning to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 1 )); then
-        echo -e "\033[1;35m WARN:\033[0m $*" >&2
+        echo "${TTYERR[m_B]:-} WARN:${TTYERR[n]:-} $*" >&2
     fi
 }
 
 function note ## [message..] - may print an important notice to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 2 )); then
-        echo -e "\033[1;35m NOTE:\033[0m $*" >&2
+        echo "${TTYERR[m_B]:-} NOTE:${TTYERR[n]:-} $*" >&2
     fi
 }
 
 function info ## [message..] - may print an informal message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 3 )); then
-        echo -e "\033[1;34m INFO:\033[0m $*" >&2
+        echo "${TTYERR[b_B]:-} INFO:${TTYERR[n]:-} $*" >&2
     fi
 }
 
 function debug ## [message..] - may print a debug message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 4 )); then
-        echo -e "\033[1;36mDEBUG:\033[0m $(source_info 1) $*" >&2
+        echo "${TTYERR[c_B]:-}DEBUG:${TTYERR[n]:-} $(source_info 1) $*" >&2
     fi
 }
 
 function trace ## [message] - may prints a trace message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 5 )); then
-        echo -e "\033[1;96mTRACE:\033[0m $(source_info 1) $*" >&2
+        echo "${TTYERR[C_B]:-}TRACE:${TTYERR[n]:-} $(source_info 1) $*" >&2
     fi
 }
 
