add tty_newline and dumb term detection to prevent output garbling

diff --git a/Bar.d/std_lib b/Bar.d/std_lib
--- a/Bar.d/std_lib
+++ b/Bar.d/std_lib
@@ -69,29 +69,48 @@ function called_as
 # elusive progress notice
 function progress ## [message..] -
 {
+    [[ "${TERM:-dumb}" = "dumb" ]] && return 0
     if (( BAR_CHECK_LEVEL > 0 )); then
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && tty_echo -n "${TTYERR[K_B]:-}  RUN: $*${TTYERR[cr]:-}" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && {
+            tty_newline
+            tty_echo -n "${TTYERR[K_B]:-}  RUN: $*${TTYERR[cr]:-}${TTYERR[n]:-}"
+        }
     else
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && tty_echo -n "${TTYERR[K_B]:-}  RUN: $*${TTYERR[cr]:-}" >&2
-    fi
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && {
+            tty_newline
+            tty_echo -n "${TTYERR[K_B]:-}  RUN: $*${TTYERR[cr]:-}${TTYERR[n]:-}"
+        }
+    fi >&2
 }
 
 function success ## [message..] -
 {
     if (( BAR_CHECK_LEVEL > 0 )); then
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-}CHECK:${TTYERR[n]:-} $*" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && {
+            tty_newline
+            echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-}CHECK:${TTYERR[n]:-} $*"
+        }
     else
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-}   OK:${TTYERR[n]:-} $*" >&2
-    fi
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && {
+            tty_newline
+            echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-}   OK:${TTYERR[n]:-} $*"
+        }
+    fi >&2
 }
 
 function failure ## [message..] -
 {
     if (( BAR_CHECK_LEVEL > 0 )); then
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && echo -e "${TTYERR[ce]:-}${TTYERR[K_B]:-}CHECK: ${TTYERR[__S]:-}$*${TTYERR[n]:-}" >&2
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )) && {
+            tty_newline
+            echo -e "${TTYERR[ce]:-}${TTYERR[K_B]:-}CHECK: ${TTYERR[__S]:-}$*${TTYERR[n]:-}"
+        }
     else
-        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && echo -e "${TTYERR[ce]:-}${TTYERR[r_B]:-} FAIL:${TTYERR[n]:-} $*" >&2
-    fi
+        (( "${BAR_VERBOSITY_LEVEL:-5}" > 1 )) && {
+            tty_newline
+            echo -e "${TTYERR[ce]:-}${TTYERR[r_B]:-} FAIL:${TTYERR[n]:-} $*"
+        }
+    fi >&2
 }
 
 function uncond_call ## <rc> [message..] -
@@ -99,12 +118,13 @@ function uncond_call ## <rc> [message..] -
     declare -i rc="$1"
     shift
     if (( "${BAR_VERBOSITY_LEVEL:-5}" > 2 )); then
+        tty_newline
         if (( rc == 0 )); then
-            echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-} EVAL:${TTYERR[n]:-} $*" >&2
+            echo -e "${TTYERR[ce]:-}${TTYERR[g_B]:-} EVAL:${TTYERR[n]:-} $*"
         else
-            echo -e "${TTYERR[ce]:-}${TTYERR[K_B]:-} EVAL:${TTYERR[n]:-} $*" >&2
+            echo -e "${TTYERR[ce]:-}${TTYERR[K_B]:-} EVAL:${TTYERR[n]:-} $*"
         fi
-    fi
+    fi >&2
 }
 
 function rule_autoload ## <name>
diff --git a/bar b/bar
--- a/bar
+++ b/bar
@@ -183,59 +183,72 @@ function require
     return $rc
 }
 
+# placeholder, overwritten by tty_lib when present
+tty_newline() { :; }
+
 function DBG ## [message..] - for print-style debugging, should not be present in production code
 {
-    echo "${TTYERR[r_R]:-}${TTYERR[__B]:-}  DBG:${TTYERR[n]:-} $(source_info 1) $*" >&2
+    {
+        tty_newline
+        echo "${TTYERR[r_R]:-}${TTYERR[__B]:-}  DBG:${TTYERR[n]:-} $(source_info 1) $*"
+    } >&2
 }
 
 function die ## [message..] - prints 'message' to stderr and exits with failure
 {
     if (( BAR_VERBOSITY_LEVEL > 0 )); then
-        echo "${TTYERR[R_B]:-}PANIC:${TTYERR[n]:-} $(source_info 1) $*" >&2
-    fi
+        tty_newline
+        echo "${TTYERR[R_B]:-}PANIC:${TTYERR[n]:-} $(source_info 1) $*"
+    fi >&2
     exit 1
 }
 
 function error ## [message..] - may print a error message to stderr and return failure
 {
     if (( BAR_VERBOSITY_LEVEL > 0 )); then
-        echo "${TTYERR[r_B]:-}ERROR:${TTYERR[n]:-} $(source_info 1) $*" >&2
-    fi
+        tty_newline
+        echo "${TTYERR[r_B]:-}ERROR:${TTYERR[n]:-} $(source_info 1) $*"
+    fi >&2
 }
 
 function warn ## [message..] - may print an warning to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 1 )); then
+        tty_newline
         echo "${TTYERR[m_B]:-} WARN:${TTYERR[n]:-} $*" >&2
-    fi
+    fi >&2
 }
 
 function note ## [message..] - may print an important notice to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 2 )); then
-        echo "${TTYERR[m_B]:-} NOTE:${TTYERR[n]:-} $*" >&2
-    fi
+        tty_newline
+        echo "${TTYERR[m_B]:-} NOTE:${TTYERR[n]:-} $*"
+    fi >&2
 }
 
 function info ## [message..] - may print an informal message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 3 )); then
-        echo "${TTYERR[b_B]:-} INFO:${TTYERR[n]:-} $*" >&2
-    fi
+        tty_newline
+        echo "${TTYERR[b_B]:-} INFO:${TTYERR[n]:-} $*"
+    fi >&2
 }
 
 function debug ## [message..] - may print a debug message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 4 )); then
-        echo "${TTYERR[c_B]:-}DEBUG:${TTYERR[n]:-} $(source_info 1) $*" >&2
-    fi
+        tty_newline
+        echo "${TTYERR[c_B]:-}DEBUG:${TTYERR[n]:-} $(source_info 1) $*"
+    fi >&2
 }
 
 function trace ## [message] - may prints a trace message to stderr
 {
     if (( BAR_VERBOSITY_LEVEL > 5 )); then
-        echo "${TTYERR[C_B]:-}TRACE:${TTYERR[n]:-} $(source_info 1) $*" >&2
-    fi
+        tty_newline
+        echo "${TTYERR[C_B]:-}TRACE:${TTYERR[n]:-} $(source_info 1) $*"
+    fi >&2
 }
 
 bar_main "$@"
